name: commitfiles
on: [push]

# jobs:
#   job1:
#     runs-on: [ubuntu-latest]
#     steps:
#       - name: checkout
#         uses: actions/checkout@v2
#       - name: Make Request
#         id: myRequest
#         uses: fjogeleit/http-request-action@master
#         with:
#           url: "https://costellocoding.com/ifm/github_json/"
#       - name: Show Response
#         run: echo ${{ steps.myRequest.outputs.response }} >> menu.json
#       - name: move to dir # Move the generated files into output folder
#         run: |
#           mkdir -p output
#           yes| cp -rf menu.json ./output/
#       - name: Commit files # commit the output folder
#         run: |
#           git config --local user.email "costellos@costellocoding.com"
#           git config --local user.name "GitHub Action test"
#           git add ./output
#           git commit -m "Update Menu Json Data"
#       - name: Push changes # push the output folder to your repo
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           force: true
