

name: Update Json Menu
on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup PHP without any shared extensions except mbstring
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: none, mbstring
    - name: Run PHP and Update Menu
      run: |
        php "./php/index.php"
        curl "./php/index.php" | jq . > menu.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git diff --quiet || (git add -A && git commit -m "Updated with latest")
        git push
